require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
require "user.custom.functions"
require "user.neovide-options"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.auto-session"
spec "user.lspconfig"
spec "user.lsp_signature"
spec "user.none-ls"
spec "user.mason-null-ls"
spec "user.blink"
spec "user.extras.copilot"
spec "user.telescope"
spec "user.telescope-tabs"
spec "user.illuminate"
spec "user.diffview"
spec "user.blame"
spec "user.gitsigns"
spec "user.fugitive"
spec "user.whichkey"
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.dropbar"
spec "user.harpoon"
spec "user.flash"
spec "user.autopairs"
spec "user.vim-better-whitespace"
spec "user.neogit"
spec "user.indentline"
spec "user.toggleterm"
spec "user.trouble"
spec "user.rainbow-delimiters"
spec "user.undotree"
spec "user.noice"
spec "user.snacks"
spec "user.extras.bqf"
spec "user.extras.dressing"
spec "user.extras.fidget"
spec "user.extras.eyeliner"
spec "user.extras.modicator"
spec "user.extras.neotab"
spec "user.extras.tabby"
spec "user.extras.ufo"
spec "user.extras.beacon"
spec "user.extras.actions-preview"
spec "user.extras.goto-preview"
spec "user.extras.treesitter-context"
spec "user.extras.context-vt"
spec "user.extras.tiny-inline-diagnostic"
spec "user.extras.render-markdown"
require "user.lazy"
-- Disabled
-- spec "user.alpha" -- Use snacks.dashboard instead
-- spec "user.schemastore"
-- spec "user.cmp" -- use blink instead
-- spec "user.project"
-- spec "user.navic" -- dropbar is better
-- spec "user.extras.navbuddy"
-- spec "user.extras.neoscroll" -- Use snacks.scroll instead
-- spec "user.extras.neodev"
-- spec "user.extras.oil" --nvim-tree is sufficient for most cases
-- spec "user.feline" -- Use lualine instead
--spec "user.neotest"
